### ISSUE TITLE
Reusable New Connection Widget Flow

### ISSUE THREAD

**Issue by nhenin** [input-output-hk/marlowe-order-book-swap#49]
We need to modify the flow in the same spirit as the `token plans` prototype
1. End Users needs to understand/see what is the goal of this prototype when directly landing on the page for the first time
2. switch from a wallet to another smoothly without loosing the overall focus of the page
3. End Users should see their ₳ balance instead of my address and also see to which wallet I am connected.. This balance display should react to change

We'd like to make it reusable for users of the ts-sdk... This should be an independent react component that will be reused for all our prototypes

- Execution Proposition 

1. Start with the Token Plan prototype : 
- [ ] Extract the component into a repository (Where ?? Discussion Happening in Slack )
- [ ] Replace the existing logic  : https://github.com/input-output-hk/marlowe-token-plans/issues/34
2. Integrate the new component here (Order Book Swap Repository) 
3. Let's update the Payouts Prototype as well (Something I (@nhenin) can do...)

**Comment by mikarasv** [comment]
Solved on PR #66
