### ISSUE TITLE
Check contracts state

### ISSUE THREAD

**Issue by FranZavalla** [input-output-hk/marlowe-order-book-swap#95]
Before any input (accept swap, retract, ...), check if the contract is in the correct state.

For example, [this contract](https://preprod.marlowescan.com/contractView?tab=info&contractId=3d4e5584ec802f8fcd841f67d39ad474cfbf91e2092a96517eb1528512ab9fcb%231) has no deposit from the `provider` and the `Retract` option is available (An error occurs). Check the state with `getState()` from the TS-SDK and disable the button to prevent that behavior.

**Comment by mikarasv** [comment]
solved on PR #98
